const langDemoMap = 
[
    { language: 'Javascript', demo: [`for(let i=1;i<=5;i++){let row='';for(let j=1;j<=i;j++){row+=\`\${j} \`}console.log(row)}for(let i=5;i>=1;i--){let row='';for(let j=i;j>=1;j--){row+=\`\${j} \`}console.log(row)}`] },
    { language: 'Typescript', demo: [`for (let i: number = 1; i <= 5; i++) {let row: string = '';for (let j: number = 1; j <= i; j++) {row += \`\${j} \`}console.log(row)}for (let i: number = 5; i >= 1; i--) {let row: string = '';for (let j: number = i; j >= 1; j--) {row += \`\${j} \`}console.log(row)}`] },
    { language: 'React', demo: [`import React, { useState } from 'react';function App() {const [count, setCount] = useState(0);return (<div><h1>React App</h1><p>Count: {count}</p><button onClick={() => setCount(count + 1)}>Increment</button></div>);}`, `import React, { useState, ReactElement } from 'react';function App(): ReactElement {const [count, setCount] = useState<number>(0);return (<div><h1>React App</h1><p>Count: {count}</p><button onClick={() => setCount(count + 1)}>Increment</button></div>);}`] },
    { language: 'HTML', demo: [`<html><head><title>My HTML Page</title></head><body><h1>Hello, World!</h1><p>This is a simple HTML page.</p></body></html>`, `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet"><link rel="stylesheet" href="styles.css"><title>Alphabet Generator 8x8</title></head><body><div class="container"><div class="header"><p>CLM</p></div><div class="content"><div class="dn" id="ID_KEYBOARD_CONTAINER"><div class="alphabet-controls" id="ID_KEYBOARD_CONTROLS"></div></div><div class="df-c"><div class="led-panel-controller"><button id="ID_LED_TRASH" class="led-panel-clear led-controller-btn"><img src="trash-2.svg"></button><button id="ID_LED_RESTORE" class="led-panel-restore led-controller-btn"><img src="refresh-ccw.svg"></button><button id="ID_LED_LEFT_SHIFT" class="led-panel-left led-controller-btn"><img src="arrow-left.svg"/></button><button id="ID_LED_RIGHT_SHIFT" class="led-panel-right led-controller-btn"><img src="arrow-left.svg"/></button><label id="ID_LED_COLOR_L" class="led-panel-color-label"><input type="color" id="ID_LED_COLOR" class = "led-panel-color" value="#FF0050"/></label><button class="led-panel-keyboard led-controller-btn" id="ID_LED_KEYBOARD"><img src="1293306.svg"></button></div></div><div class="led-panel-container"><div class="led-panel" id="ID_LED_PANEL"></div></div><div class="df-c"><div class="led-panel-controller"><button class="led-panel-rotate led-controller-btn" id="ID_ROTATE"><img src="rotate-cw.svg"></button><button class="led-panel-type led-controller-btn" id="ID_DWN_TYPE"><p>C++</p></button><button class="led-panel-dwn led-controller-btn" id="ID_LED_DWN"><img src="download.svg"/></button><div class="led-panel-dwn-all led-controller-btn" id="ID_LED_DWN_ALL"><img src="file-text.svg"></div></div></div><div id="ID_LED_CHASER_CONTAINER" class="led-chaser-container"><div id="ID_LED_CHASER_PANEL" class="led-chaser-panel"></div></div><div class="df-c"><div class="led-panel-speed-controller"><input id="ID_LED_CHASE_SPEED" class="slider led-chase-speed" type="range" min="0" max="100" value="90"><input id="ID_LED_CHASE_TEXT" class="led-input-textbox" type="text" placeholder="Enter Text"><button id="ID_LED_CHASE_TEXT_SUBMIT" class="led-controller-btn led-submit-btn"><p>Submit</p></button></div></div></div></div><script src="script.js"></script></body></html>`] },
    { language: 'Angular', demo: [`import { Component } from '@angular/core';@Component({selector: 'app-root',template: '<h1>Hello, Angular!</h1><p>Multi-line Angular code without indentation</p>',styles: ['.custom-style { color: blue; }']})export class AppComponent {isButtonDisabled = false;items = [1, 2, 3, 4, 5];constructor() {setTimeout(() => {this.isButtonDisabled = true;}, 3000);}onButtonClick() {console.log('Button clicked!');}}`, `class AppComponent{constructor(){this.selector='app-root';this.template='<h1>Hello, Angular!</h1><p>Multi-line Angular code without indentation</p>';this.styles=['.custom-style { color: blue; }'];this.isButtonDisabled=false;this.items=[1,2,3,4,5];setTimeout(()=>{this.isButtonDisabled=true;},3000);}onButtonClick(){console.log('Button clicked!');}}const componentMetadata={selector:'app-root',template:'<h1>Hello, Angular!</h1><p>Multi-line Angular code without indentation</p>',styles:['.custom-style { color: blue; }']};AppComponent.annotations=[new Component(componentMetadata)];`] },
    { language: 'Vue', demo: [`<script setup>import { ref } from 'vue';const message = ref('Hello World!');function reverseMessage() {message.value = message.value.split('').reverse().join('')}function notify() {alert('navigation was prevented.')}</script><template><h1>{{ message }}</h1><button @click="reverseMessage">Reverse Message</button><button @click="message += '!'">Append "!"</button><a href="https://vuejs.org" @click.prevent="notify">A link with e.preventDefault()</a></template><style>button,a {display: block;margin-bottom: 1em;}</style>`] },
    { language: 'CSS', demo: [`body{font-family:sans-serif;margin:0;padding:0;background-color:#f0f0f0;color:#333}h1{color:blue}p{font-size:16px;line-height:1.5}a{color:purple;text-decoration:none}a:hover{border-bottom:1px solid purple}header{background-color:#333;color:white;padding:10px;text-align:center}nav{float:left;width:30%;padding:20px}section{float:left;width:40%;padding:20px}article{float:right;width:30%;padding:20px}footer{clear:both;background-color:#333;color:white;text-align:center;padding:10px}`] },
    { language: 'SCSS', demo: [`$font-family:sans-serif;$primary-color:#333;$accent-color:purple;body{font-family:$font-family;margin:0;padding:0;background-color:#f0f0f0;color:#333}h1{color:blue}p{font-size:16px;line-height:1.5}a{color:$accent-color;text-decoration:none}&:hover{border-bottom:1px solid $accent-color}header{background-color:$primary-color;color:white;padding:10px;text-align:center}nav{float:left;width:30%;padding:20px}section{float:left;width:40%;padding:20px}article{float:right;width:30%;padding:20px}footer{clear:both;background-color:$primary-color;color:white;text-align:center;padding:10px}`] },
    { language: 'Less', demo: [`@font-family: sans-serif; @primary-color: #333; @accent-color: purple; body { font-family: @font-family; margin: 0; padding: 0; background-color: #f0f0f0; color: #333; } h1 { color: blue; } p { font-size: 16px; line-height: 1.5; } a { color: @accent-color; text-decoration: none; &:hover { border-bottom: 1px solid @accent-color; } } header { background-color: @primary-color; color: white; padding: 10px; text-align: center; } nav { float: left; width: 30%; padding: 20px; } section { float: left; width: 40%; padding: 20px; } article { float: right; width: 30%; padding: 20px; } footer { clear: both; background-color: @primary-color; color: white; text-align: center; padding: 10px; }`] },
    { language: 'JSON', demo: [`{"firstName":"John","lastName":"Doe","age":30,"email":"john.doe@example.com","address":{"street":"123 Main Street","city":"Anytown","state":"CA","zipCode":"12345"},"isStudent":false,"grades":[90,85,92,88],"courses":{"math":"A","english":"B","history":"A-"}}`] },
    { language: 'XML', demo: [`<?xml version="1.0" encoding="UTF-8" ?><root><firstName>John</firstName><lastName>Doe</lastName><age>30</age><email>john.doe@example.com</email><address><street>123 Main Street</street><city>Anytown</city><state>CA</state><zipCode>12345</zipCode></address><isStudent>false</isStudent><grades>90</grades><grades>85</grades><grades>92</grades><grades>88</grades><courses><math>A</math><english>B</english><history>A-</history></courses></root>`] },
    { language: 'Graphql', demo: [`query{user(id:"123"){firstName lastName age email address{street city state zipCode}isStudent grades{math english history}courses{math english history}}}`] }
];
const randInt = (max) => {
    return Math.floor(Math.random()*max);
}
export default function ExampleGen(language) {
    const index = langDemoMap.findIndex(item=>item.language === language);
    if(index !== -1){
        const length = langDemoMap[index].demo.length;
        return langDemoMap[index].demo[randInt(length)];
    }
    throw new Error('Unsupported Language');
}